BARRIO_MAPPING = {
    0: 'Baró de Viver',
    1: 'Can Baró',
    2: 'Can Peguera',
    3: 'Canyelles',
    4: 'Ciutat Meridiana',
    5: 'Desconegut',
    6: 'Diagonal Mar i el Front Marítim del Poblenou',
    7: 'Horta',
    8: 'Hostafrancs',
    9: 'Montbau',
    10: 'Navas',
    11: 'Pedralbes',
    12: 'Porta',
    13: 'Provençals del Poblenou',
    14: 'Sant Andreu',
    15: 'Sant Antoni',
    16: 'Sant Genís dels Agudells',
    17: 'Sant Gervasi - Galvany',
    18: 'Sant Gervasi - la Bonanova',
    19: 'Sant Martí de Provençals',
    20: 'Sant Pere, Santa Caterina i la Ribera',
    21: 'Sants',
    22: 'Sants - Badal',
    23: 'Sarrià',
    24: 'Torre Baró',
    25: 'Vallbona',
    26: 'Vallcarca i els Penitents',
    27: 'Vallvidrera, el Tibidabo i les Planes',
    28: 'Verdun',
    29: 'Vilapicina i la Torre Llobeta',
    30: 'el Baix Guinardó',
    31: 'el Barri Gòtic',
    32: 'el Besòs i el Maresme',
    33: 'el Bon Pastor',
    34: 'el Camp d'en Grassot i Gràcia Nova',
    35: 'el Camp de l'Arpa del Clot',
    36: 'el Carmel',
    37: 'el Clot',
    38: 'el Coll',
    39: 'el Congrés i els Indians',
    40: 'el Fort Pienc',
    41: 'el Guinardó',
    42: 'el Parc i la Llacuna del Poblenou',
    43: 'el Poble Sec',
    44: 'el Poble-sec',
    45: 'el Poblenou',
    46: 'el Putxet i el Farró',
    47: 'el Raval',
    48: 'el Turó de la Peira',
    49: 'l'Antiga Esquerra de l'Eixample',
    50: 'la Barceloneta',
    51: 'la Bordeta',
    52: 'la Clota',
    53: 'la Dreta de l'Eixample',
    54: 'la Font d'en Fargues',
    55: 'la Font de la Guatlla',
    56: 'la Guineueta',
    57: 'la Marina de Port',
    58: 'la Marina del Prat Vermell',
    59: 'la Maternitat i Sant Ramon',
    60: 'la Nova Esquerra de l'Eixample',
    61: 'la Prosperitat',
    62: 'la Sagrada Família',
    63: 'la Sagrera',
    64: 'la Salut',
    65: 'la Teixonera',
    66: 'la Trinitat Nova',
    67: 'la Trinitat Vella',
    68: 'la Vall d'Hebron',
    69: 'la Verneda i la Pau',
    70: 'la Vila Olímpica del Poblenou',
    71: 'la Vila de Gràcia',
    72: 'les Corts',
    73: 'les Roquetes',
    74: 'les Tres Torres',
}